using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Windows.Forms;

namespace MusicAssistant {
 public sealed partial class MainForm {
  bool buildingUi,previewMode,showCards=true;Track cardSelected;string statusTab="全部";
  readonly TextBox songSearch=new TextBox();readonly ComboBox platformFilter=new ComboBox();
  readonly FlowLayoutPanel albumWall=new FlowLayoutPanel();readonly Dictionary<string,SoftButton> navigation=new Dictionary<string,SoftButton>();
  readonly FlowLayoutPanel collectionList=new FlowLayoutPanel();readonly List<SoftButton> statusButtons=new List<SoftButton>();
  readonly Label breadcrumb=new Label(),storageCount=new Label(),activityCaption=new Label(),selectionCaption=new Label();
  readonly ToolTip tips=new ToolTip();MetricTile[] metricItems=new MetricTile[4];Panel taskStage,gridSurface,emptyState;
  SoftButton cardToggle,tableToggle;string dataNotice="";

  string ButtonIcon(string text){if(text.Contains("目录")||text.Contains("文件"))return "folder";if(text.Contains("密钥"))return "key";if(text.Contains("日志"))return "list";if(text.Contains("读取")||text.Contains("链接"))return "link";if(text.Contains("导入")||text.Contains("添加"))return "plus";if(text.Contains("处理"))return "play";if(text.Contains("设置"))return "settings";return null;}
  void InitializeShell(){
   var sidebar=new Panel{Dock=DockStyle.Left,Width=214,BackColor=Color.White,Padding=new Padding(14,23,14,14)};
   var host=new Panel{Dock=DockStyle.Fill,BackColor=background};Controls.Add(host);Controls.Add(sidebar);
   content.Dock=DockStyle.Fill;content.Padding=new Padding(26,18,26,17);content.BackColor=background;host.Controls.Add(content);
   var topbar=new Panel{Dock=DockStyle.Top,Height=56,BackColor=Color.White,Padding=new Padding(26,0,24,0)};topbar.Paint+=(s,e)=>{using(var p=new Pen(UiTheme.Line))e.Graphics.DrawLine(p,0,55,topbar.Width,55);};host.Controls.Add(topbar);
   breadcrumb.Dock=DockStyle.Fill;breadcrumb.ForeColor=muted;breadcrumb.TextAlign=ContentAlignment.MiddleLeft;breadcrumb.Font=new Font(Font.FontFamily,8.5f);topbar.Controls.Add(breadcrumb);
   var topRight=new FlowLayoutPanel{Dock=DockStyle.Right,Width=250,Padding=new Padding(0,10,0,0),FlowDirection=FlowDirection.RightToLeft,WrapContents=false};topbar.Controls.Add(topRight);
   var prefs=Button("设置",()=>Switch("设置与帮助"),84,false);((SoftButton)prefs).Quiet=true;topRight.Controls.Add(prefs);
   var mode=Label(previewMode?"界面预览 · 0.5":"保真处理 · 0.5",8.5f,Color.FromArgb(108,140,120),145,36);mode.TextAlign=ContentAlignment.MiddleRight;topRight.Controls.Add(mode);
   var side=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=6,BackColor=Color.White};side.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));foreach(float h in new[]{82f,25f,144f,36f,0f,147f})side.RowStyles.Add(new RowStyle(h==0?SizeType.Percent:SizeType.Absolute,h==0?100:h));sidebar.Controls.Add(side);
   var brand=new Panel{Dock=DockStyle.Fill,BackColor=Color.White};brand.Controls.Add(new BrandMark{Location=new Point(7,2)});var brandTitle=Label("音乐助手",17,ink,130,32);brandTitle.Location=new Point(58,0);brand.Controls.Add(brandTitle);var tagline=Label("你的歌单，随身听",8,muted,130,24);tagline.Location=new Point(58,32);brand.Controls.Add(tagline);side.Controls.Add(brand,0,0);
   side.Controls.Add(Label("我的音乐库",8,Color.FromArgb(165,173,184),175,25),0,1);
   var nav=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,BackColor=Color.White};
   foreach(var entry in new[]{new[]{"歌单任务","歌单资料库","grid"},new[]{"处理历史","处理历史","history"},new[]{"设置与帮助","设置与帮助","settings"}}){string target=entry[0];var b=(SoftButton)Button(entry[1],()=>Switch(target),178,false);b.Height=44;b.Icon=entry[2];b.LeftAligned=true;b.Quiet=true;b.Margin=new Padding(0,0,0,4);navigation[target]=b;nav.Controls.Add(b);}side.Controls.Add(nav,0,2);
   var collectionHeader=new Panel{Dock=DockStyle.Fill,BackColor=Color.White};collectionHeader.Controls.Add(Label("我的歌单",8,muted,130,35));var add=(SoftButton)Button("",()=>ShowImportMenu(null),32,false);add.Icon="plus";add.Quiet=true;add.Location=new Point(150,0);collectionHeader.Controls.Add(add);side.Controls.Add(collectionHeader,0,3);
   collectionList.Dock=DockStyle.Fill;collectionList.FlowDirection=FlowDirection.TopDown;collectionList.WrapContents=false;collectionList.AutoScroll=true;collectionList.BackColor=Color.White;side.Controls.Add(collectionList,0,4);
   var sideBottom=new Panel{Dock=DockStyle.Fill,BackColor=Color.White};var card=new SurfacePanel{Location=new Point(0,3),Size=new Size(183,113),SurfaceColor=background,BackColor=Color.White};card.Controls.Add(Label("本机处理记录",8,muted,150,26));card.Controls[0].Location=new Point(13,5);storageCount.SetBounds(13,32,160,32);storageCount.BackColor=Color.Transparent;storageCount.Font=new Font(Font.FontFamily,16,FontStyle.Bold);storageCount.ForeColor=ink;card.Controls.Add(storageCount);var storage=(SoftButton)Button("存储设置",()=>Switch("设置与帮助"),158,false);storage.Quiet=true;storage.LeftAligned=true;storage.Icon="settings";storage.SetBounds(10,70,163,32);card.Controls.Add(storage);sideBottom.Controls.Add(card);var local=Label("数据保存在你的电脑",7.5f,Color.FromArgb(159,170,182),180,25);local.Location=new Point(8,120);sideBottom.Controls.Add(local);side.Controls.Add(sideBottom,0,5);
  }
  void RefreshSidebar(){collectionList.SuspendLayout();foreach(Control c in collectionList.Controls.Cast<Control>().ToArray())c.Dispose();collectionList.Controls.Clear();
   if(playlists.Count==0){var hint=Label("导入第一份歌单\n让喜欢的音乐随身同行",8.5f,muted,163,70);hint.Margin=Padding.Empty;collectionList.Controls.Add(hint);}else for(int i=0;i<playlists.Count;i++){int index=i;var p=playlists[i];var b=(SoftButton)Button(p.Name,()=>{if(busy)return;if(view!="歌单任务"&&view!="任务")Switch("歌单任务");listSelector.SelectedIndex=index;},173,false);b.Icon="folder";b.Quiet=true;b.Chosen=index==listSelector.SelectedIndex;b.LeftAligned=true;b.Height=37;b.Margin=new Padding(0,0,0,3);b.MouseUp+=(sender,args)=>{if(args.Button==MouseButtons.Right)ShowPlaylistMenu(index,b);};tips.SetToolTip(b,p.Name+" · "+p.Tracks.Count+" 首");collectionList.Controls.Add(b);}collectionList.ResumeLayout();storageCount.Text=store.History.Select(h=>h.RelativePath).Distinct().Count()+" 首";
   string key=view=="任务"?"歌单任务":view;foreach(var pair in navigation){pair.Value.Chosen=pair.Key==key;pair.Value.Invalidate();}breadcrumb.Text="我的音乐库    ›    "+(key=="歌单任务"?"歌单资料库":key);
  }
  void ReleasePage(){Control[] reusable={subtitle,link,listSelector,grid,log,run,cancel,progress,historySearch,output,recycle,flac,sourceDirs,historyGrid,songSearch,platformFilter,albumWall,activityCaption,selectionCaption};foreach(var c in reusable)if(c.Parent!=null)c.Parent.Controls.Remove(c);foreach(Control c in content.Controls.Cast<Control>().ToArray())c.Dispose();content.Controls.Clear();}
  TableLayoutPanel Base(string title,string description){ReleasePage();var shell=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=2,BackColor=background,Margin=Padding.Empty};shell.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));shell.RowStyles.Add(new RowStyle(SizeType.Absolute,72));shell.RowStyles.Add(new RowStyle(SizeType.Percent,100));content.Controls.Add(shell);
   var head=new Panel{Dock=DockStyle.Fill,BackColor=background};head.Controls.Add(Label(title,22,ink,480,40));subtitle.Text=description;subtitle.Font=new Font(Font.FontFamily,8.5f);subtitle.ForeColor=muted;subtitle.SetBounds(0,40,900,24);head.Controls.Add(subtitle);shell.Controls.Add(head,0,0);return shell;}
  void Switch(string name){if(busy)return;view=name;buildingUi=true;if(name=="处理历史")BuildHistory();else if(name=="设置与帮助")BuildSettings();else BuildTasks();buildingUi=false;RefreshSidebar();}
  public void ShowPreviewPage(string name){if(name=="歌曲列表"){showCards=false;Switch("歌单任务");}else Switch(name);}
  public void SetDataLocationNotice(string notice){dataNotice=notice;Append(notice);}
  void InputStyle(TextBox box){box.BorderStyle=BorderStyle.None;box.BackColor=Color.FromArgb(248,249,251);box.ForeColor=ink;box.Font=new Font(Font.FontFamily,9);}
  SurfacePanel InputWrap(TextBox box,string icon){InputStyle(box);var p=new SurfacePanel{Dock=DockStyle.Fill,Radius=7,SurfaceColor=box.BackColor,BackColor=Color.White};p.Controls.Add(box);p.Resize+=(s,e)=>{box.SetBounds(string.IsNullOrEmpty(icon)?12:34,Math.Max(9,(p.Height-box.PreferredHeight)/2),Math.Max(30,p.Width-(string.IsNullOrEmpty(icon)?24:45)),box.PreferredHeight);};if(!string.IsNullOrEmpty(icon))p.Paint+=(s,e)=>UiIcons.Draw(e.Graphics,icon,new Rectangle(11,(p.Height-15)/2,15,15),muted);return p;}
  void ComboStyle(ComboBox combo){combo.DropDownStyle=ComboBoxStyle.DropDownList;combo.FlatStyle=FlatStyle.Flat;combo.BackColor=Color.White;combo.ForeColor=Color.FromArgb(94,111,129);combo.Font=new Font(Font.FontFamily,9);}
  void BuildTasks(){buildingUi=true;mutable.Clear();view="歌单任务";var shell=Base("歌单","保留每份源音质，整理成适合 Walkman 的音乐与播放列表。");
   var body=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=6,Margin=Padding.Empty};body.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));foreach(float h in new[]{94f,67f,102f,0f,39f,62f})body.RowStyles.Add(new RowStyle(h==0?SizeType.Percent:SizeType.Absolute,h==0?100:h));shell.Controls.Add(body,0,1);
   var metrics=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=4,RowCount=1,Margin=new Padding(0,0,0,13)};metrics.RowStyles.Add(new RowStyle(SizeType.Percent,100));for(int i=0;i<4;i++){metrics.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,25));metricItems[i]=new MetricTile{Dock=DockStyle.Fill,Margin=new Padding(i==0?0:6,0,i==3?0:6,0),Caption=new[]{"歌单中的歌曲","已完成处理","历史直接复用","等待补齐"}[i],Icon=new[]{"music","check","history","download"}[i],Tint=i==1?Color.FromArgb(115,162,135):accent};metrics.Controls.Add(metricItems[i],i,0);}body.Controls.Add(metrics,0,0);
   var linkCard=new SurfacePanel{Dock=DockStyle.Fill,BackColor=background,Margin=new Padding(0,0,0,13),Padding=new Padding(14,10,14,10)};var linkRow=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=4,RowCount=1,Margin=Padding.Empty};linkRow.BackColor=Color.White;linkRow.RowStyles.Add(new RowStyle(SizeType.Percent,100));linkRow.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,75));linkRow.BackColor=Color.White;linkRow.RowStyles.Add(new RowStyle(SizeType.Percent,100));linkRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));linkRow.BackColor=Color.White;linkRow.RowStyles.Add(new RowStyle(SizeType.Percent,100));linkRow.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,129));linkRow.BackColor=Color.White;linkRow.RowStyles.Add(new RowStyle(SizeType.Percent,100));linkRow.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,110));linkCard.Controls.Add(linkRow);linkRow.Controls.Add(Label("歌单链接",9,muted,74,34),0,0);var linkWrap=InputWrap(link,"link");linkWrap.Margin=new Padding(0,0,12,0);linkRow.Controls.Add(linkWrap,1,0);var read=Button("读取歌单",()=>ReadLink(),117,true);read.Dock=DockStyle.Fill;read.Margin=new Padding(0,0,10,0);linkRow.Controls.Add(read,2,0);var imports=Button("导入",()=>ShowImportMenu(null),105,false);((SoftButton)imports).Icon="plus";imports.Dock=DockStyle.Fill;imports.Margin=Padding.Empty;linkRow.Controls.Add(imports,3,0);mutable.Add(link);mutable.Add(read);mutable.Add(imports);body.Controls.Add(linkCard,0,1);
   var filter=new SurfacePanel{Dock=DockStyle.Fill,BackColor=background,Padding=new Padding(13,9,13,9),Margin=new Padding(0,0,0,14)};var frows=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=2,ColumnCount=1,Margin=Padding.Empty};frows.BackColor=Color.White;frows.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));frows.RowStyles.Add(new RowStyle(SizeType.Absolute,35));frows.BackColor=Color.White;frows.RowStyles.Add(new RowStyle(SizeType.Percent,100));filter.Controls.Add(frows);
   var top=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=1,Margin=Padding.Empty};top.BackColor=Color.White;top.RowStyles.Add(new RowStyle(SizeType.Percent,100));top.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,365));top.BackColor=Color.White;top.RowStyles.Add(new RowStyle(SizeType.Percent,100));top.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));var tabs=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=false,Margin=Padding.Empty,BackColor=Color.White};statusButtons.Clear();foreach(string name in new[]{"全部","待处理","已完成","历史复用","需补齐"}){string captured=name;var b=(SoftButton)Button(name,()=>{statusTab=captured;ApplyFilters();},name.Length>3?80:66,false);b.Icon=null;b.Quiet=true;b.Chosen=statusTab==name;b.Height=31;b.Margin=new Padding(0,0,3,0);statusButtons.Add(b);tabs.Controls.Add(b);}top.Controls.Add(tabs,0,0);var searchWrap=InputWrap(songSearch,"search");searchWrap.Margin=new Padding(8,0,0,3);songSearch.TextChanged-=SearchChanged;songSearch.TextChanged+=SearchChanged;top.Controls.Add(searchWrap,1,0);frows.Controls.Add(top,0,0);
   var bottom=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=7,RowCount=1,Margin=new Padding(0,6,0,0)};bottom.BackColor=Color.White;bottom.RowStyles.Add(new RowStyle(SizeType.Percent,100));bottom.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,54));bottom.BackColor=Color.White;bottom.RowStyles.Add(new RowStyle(SizeType.Percent,100));bottom.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));bottom.BackColor=Color.White;bottom.RowStyles.Add(new RowStyle(SizeType.Percent,100));bottom.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,41));bottom.BackColor=Color.White;bottom.RowStyles.Add(new RowStyle(SizeType.Percent,100));bottom.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,130));bottom.BackColor=Color.White;bottom.RowStyles.Add(new RowStyle(SizeType.Percent,100));bottom.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,143));bottom.BackColor=Color.White;bottom.RowStyles.Add(new RowStyle(SizeType.Percent,100));bottom.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,40));bottom.BackColor=Color.White;bottom.RowStyles.Add(new RowStyle(SizeType.Percent,100));bottom.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,40));bottom.Controls.Add(Label("歌单",8.5f,muted,50,28),0,0);ComboStyle(listSelector);listSelector.Dock=DockStyle.Fill;listSelector.Margin=new Padding(0,1,15,0);listSelector.SelectedIndexChanged-=SelectionChanged;listSelector.SelectedIndexChanged+=SelectionChanged;bottom.Controls.Add(listSelector,1,0);bottom.Controls.Add(Label("平台",8.5f,muted,40,28),2,0);ComboStyle(platformFilter);if(platformFilter.Items.Count==0){platformFilter.Items.AddRange(new object[]{"全部平台","QQ音乐","网易云音乐","本地音乐"});platformFilter.SelectedIndex=0;}platformFilter.SelectedIndexChanged-=SearchChanged;platformFilter.SelectedIndexChanged+=SearchChanged;platformFilter.Dock=DockStyle.Fill;platformFilter.Margin=new Padding(0,1,9,0);bottom.Controls.Add(platformFilter,3,0);var dirs=Button("下载目录",ChooseSourceFolder,136,false);dirs.Dock=DockStyle.Fill;dirs.Height=29;dirs.Margin=new Padding(0,0,10,0);bottom.Controls.Add(dirs,4,0);mutable.Add(dirs);
   cardToggle=(SoftButton)Button("",()=>SetView(true),32,false);cardToggle.Icon="grid";cardToggle.Quiet=true;cardToggle.Chosen=showCards;cardToggle.Dock=DockStyle.Fill;cardToggle.Margin=new Padding(0,0,5,0);tableToggle=(SoftButton)Button("",()=>SetView(false),32,false);tableToggle.Icon="list";tableToggle.Quiet=true;tableToggle.Chosen=!showCards;tableToggle.Dock=DockStyle.Fill;tableToggle.Margin=Padding.Empty;tips.SetToolTip(cardToggle,"专辑卡片视图");tips.SetToolTip(tableToggle,"歌曲列表视图");bottom.Controls.Add(cardToggle,5,0);bottom.Controls.Add(tableToggle,6,0);frows.Controls.Add(bottom,0,1);body.Controls.Add(filter,0,2);mutable.Add(listSelector);
   taskStage=new Panel{Dock=DockStyle.Fill,BackColor=background,Margin=Padding.Empty};albumWall.Dock=DockStyle.Fill;albumWall.AutoScroll=true;albumWall.WrapContents=true;albumWall.FlowDirection=FlowDirection.LeftToRight;albumWall.BackColor=background;albumWall.Padding=Padding.Empty;taskStage.Controls.Add(albumWall);gridSurface=new SurfacePanel{Dock=DockStyle.Fill,BackColor=background,Padding=new Padding(8)};grid.Columns.Clear();StyleGrid(grid);Col(grid,"歌曲","Title",25);Col(grid,"歌手","Artist",17);Col(grid,"平台","Platform",13);Col(grid,"状态","Status",14);Col(grid,"说明","Detail",38);grid.CellDoubleClick-=GridDoubleClick;grid.CellDoubleClick+=GridDoubleClick;grid.CellToolTipTextNeeded-=GridTooltip;grid.CellToolTipTextNeeded+=GridTooltip;grid.CellPainting-=PaintStatus;grid.CellPainting+=PaintStatus;grid.CellMouseClick-=GridMenuClick;grid.CellMouseClick+=GridMenuClick;gridSurface.Controls.Add(grid);taskStage.Controls.Add(gridSurface);emptyState=EmptyPanel();taskStage.Controls.Add(emptyState);body.Controls.Add(taskStage,0,3);
   var activity=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=1,Margin=Padding.Empty};activity.RowStyles.Add(new RowStyle(SizeType.Percent,100));activity.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));activity.RowStyles.Add(new RowStyle(SizeType.Percent,100));activity.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,99));activityCaption.Dock=DockStyle.Fill;activityCaption.TextAlign=ContentAlignment.MiddleLeft;activityCaption.AutoEllipsis=true;activityCaption.ForeColor=muted;activityCaption.Font=new Font(Font.FontFamily,8);activity.Controls.Add(activityCaption,0,0);var logs=(SoftButton)Button("日志",ShowLogs,92,false);logs.Quiet=true;logs.Dock=DockStyle.Fill;activity.Controls.Add(logs,1,0);body.Controls.Add(activity,0,4);
   var dock=new SurfacePanel{Dock=DockStyle.Fill,Padding=new Padding(13,10,13,10),BackColor=background};var footer=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=5,RowCount=1,Margin=Padding.Empty};footer.BackColor=Color.White;footer.RowStyles.Add(new RowStyle(SizeType.Percent,100));footer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));footer.BackColor=Color.White;footer.RowStyles.Add(new RowStyle(SizeType.Percent,100));footer.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,155));footer.BackColor=Color.White;footer.RowStyles.Add(new RowStyle(SizeType.Percent,100));footer.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,65));footer.BackColor=Color.White;footer.RowStyles.Add(new RowStyle(SizeType.Percent,100));footer.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,147));footer.BackColor=Color.White;footer.RowStyles.Add(new RowStyle(SizeType.Percent,100));footer.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,178));dock.Controls.Add(footer);selectionCaption.Dock=DockStyle.Fill;selectionCaption.AutoEllipsis=true;selectionCaption.ForeColor=muted;selectionCaption.TextAlign=ContentAlignment.MiddleLeft;selectionCaption.Font=new Font(Font.FontFamily,8);footer.Controls.Add(selectionCaption,0,0);progress.Dock=DockStyle.Fill;progress.Height=6;progress.Margin=new Padding(4,15,14,13);footer.Controls.Add(progress,1,0);cancel.Text="停止";cancel.Dock=DockStyle.Fill;cancel.Enabled=false;cancel.FlatStyle=FlatStyle.Flat;cancel.FlatAppearance.BorderColor=UiTheme.Line;cancel.BackColor=Color.White;cancel.Margin=new Padding(0,0,8,0);cancel.Click-=CancelClick;cancel.Click+=CancelClick;footer.Controls.Add(cancel,2,0);var open=Button("打开导出目录",()=>OpenFolder(store.Settings.OutputRoot),139,false);open.Dock=DockStyle.Fill;open.Margin=new Padding(0,0,10,0);footer.Controls.Add(open,3,0);run.Text="处理全部歌单";run.Dock=DockStyle.Fill;((SoftButton)run).Primary=true;((SoftButton)run).Icon="play";run.Margin=Padding.Empty;run.Click-=RunClick;run.Click+=RunClick;footer.Controls.Add(run,4,0);body.Controls.Add(dock,0,5);
   buildingUi=false;RefreshLists();if(log.Text.Length==0)Append(audio.Available?"音频组件已就绪。导入歌单或本地音乐后开始。":"请先准备音频组件。");RefreshSidebar();
  }
  void SearchChanged(object s,EventArgs e){if(!buildingUi)BindGrid();}
  void ApplyFilters(){foreach(var b in statusButtons){b.Chosen=b.Text==statusTab;b.Invalidate();}BindGrid();}
  List<Track> VisibleTracks(){if(Current==null)return new List<Track>();string q=songSearch.Text.Trim(),p=Convert.ToString(platformFilter.SelectedItem);return Current.Tracks.Where(t=>q.Length==0||(t.Title+" "+t.Artist+" "+t.Platform).IndexOf(q,StringComparison.OrdinalIgnoreCase)>=0).Where(t=>string.IsNullOrEmpty(p)||p=="全部平台"||(p=="本地音乐"?string.IsNullOrEmpty(t.Platform):t.Platform==p)).Where(t=>statusTab=="全部"||statusTab=="已完成"&&t.Status=="已完成"||statusTab=="历史复用"&&t.Status=="历史重复"||statusTab=="待处理"&&(t.Status=="待处理"||t.Status=="处理中"||t.Status=="待重新处理")||statusTab=="需补齐"&&(t.Status=="需要密钥"||t.Status=="待官方下载"||t.Status=="失败"||t.Status=="未支持"||t.Status=="待官方确认")).ToList();}
  void UpdateCounters(){var rows=playlists.SelectMany(p=>p.Tracks).ToList();int[] values={rows.Count,rows.Count(t=>t.Status=="已完成"),rows.Count(t=>t.Status=="历史重复"),rows.Count(t=>t.Status=="需要密钥"||t.Status=="待官方下载"||t.Status=="失败"||t.Status=="未支持"||t.Status=="待官方确认")};for(int i=0;i<4;i++)if(metricItems[i]!=null&&!metricItems[i].IsDisposed){metricItems[i].Value=values[i].ToString();metricItems[i].Invalidate();}storageCount.Text=store.History.Select(h=>h.RelativePath).Distinct().Count()+" 首";if(view=="歌单任务"){subtitle.Text=Current!=null&&!string.IsNullOrEmpty(Current.ImportNotice)?Current.ImportNotice:"保留每份源音质，整理成适合 Walkman 的音乐与播放列表。";subtitle.AutoEllipsis=true;tips.SetToolTip(subtitle,subtitle.Text);}selectionCaption.Text=playlists.Count+" 份歌单 · "+rows.Count+" 首，将处理全部歌单";}
  void SetView(bool cards){var selected=Selected;showCards=cards;if(selected!=null){if(cards)SelectCard(selected);else foreach(DataGridViewRow row in grid.Rows)if(row.DataBoundItem==selected){grid.CurrentCell=row.Cells[0];break;}}if(cardToggle!=null){cardToggle.Chosen=cards;cardToggle.Invalidate();tableToggle.Chosen=!cards;tableToggle.Invalidate();}UpdateStage(VisibleTracks().Count);}
  void UpdateStage(int count){if(taskStage==null||taskStage.IsDisposed)return;albumWall.Visible=showCards&&count>0;gridSurface.Visible=!showCards&&count>0;emptyState.Visible=count==0;if(count==0)emptyState.BringToFront();else if(showCards)albumWall.BringToFront();else gridSurface.BringToFront();}
  void BuildAlbumWall(List<Track> tracks){albumWall.SuspendLayout();foreach(Control c in albumWall.Controls.Cast<Control>().ToArray())c.Dispose();albumWall.Controls.Clear();if(cardSelected==null||!tracks.Contains(cardSelected))cardSelected=tracks.FirstOrDefault();int index=0;foreach(var t in tracks){var tile=new AlbumTile(t,FindCover(t),index++){Selected=t==cardSelected};tile.Activate=SelectCard;tile.Options=(track,control)=>{SelectCard(track);ShowSongMenu(control);};tips.SetToolTip(tile,t.Title+"\n"+t.Detail);albumWall.Controls.Add(tile);}albumWall.ResumeLayout();}
  void SelectCard(Track track){cardSelected=track;foreach(AlbumTile tile in albumWall.Controls.OfType<AlbumTile>()){tile.Selected=tile.Track==track;tile.Invalidate();}selectionCaption.Text="已选择："+track.Title+" · 右键可关联文件、补密钥或重试";}
  void ShowPlaylistMenu(int index,Control owner){if(busy)return;if(view!="歌单任务"&&view!="任务")Switch("歌单任务");listSelector.SelectedIndex=index;var menu=NewMenu();MenuItem(menu,"重命名歌单",RenamePlaylist);MenuItem(menu,"保存歌单文件",SavePlaylist);MenuItem(menu,"移除歌单任务",RemovePlaylist);menu.Show(owner,new Point(10,owner.Height));}
  string FindCover(Track t){if(!string.IsNullOrEmpty(t.OutputPath))try{string folder=Path.GetDirectoryName(Files.Inside(Path.Combine(store.Settings.OutputRoot,"Music"),t.OutputPath));foreach(string name in new[]{"container-cover.jpg","container-cover.png","cover.jpg","cover.png"}){string path=Path.Combine(folder,name);if(File.Exists(path))return path;}}catch{}if(!string.IsNullOrEmpty(t.SourcePath)){string path=Path.ChangeExtension(t.SourcePath,".jpg");if(File.Exists(path))return path;path=Path.ChangeExtension(t.SourcePath,".png");if(File.Exists(path))return path;}return null;}
  Panel EmptyPanel(){var panel=new SurfacePanel{Dock=DockStyle.Fill,BackColor=background};var inner=new Panel{Size=new Size(450,210),BackColor=Color.White};inner.Controls.Add(new BrandMark{Location=new Point(203,15)});var title=Label("让喜欢的音乐，随身同行",16,ink,450,36);title.TextAlign=ContentAlignment.MiddleCenter;title.Location=new Point(0,75);inner.Controls.Add(title);var hint=Label("粘贴歌单链接，或导入已经下载的音乐",9,muted,450,33);hint.TextAlign=ContentAlignment.MiddleCenter;hint.Location=new Point(0,113);inner.Controls.Add(hint);var import=Button("导入歌单",ImportFile,130,true);import.Location=new Point(88,164);inner.Controls.Add(import);var folder=Button("音乐目录",ImportFolder,130,false);folder.Location=new Point(230,164);inner.Controls.Add(folder);panel.Controls.Add(inner);panel.Resize+=(s,e)=>inner.Location=new Point(Math.Max(0,(panel.Width-450)/2),Math.Max(0,(panel.Height-210)/2));return panel;}
  void ShowImportMenu(Control owner){if(busy)return;var menu=NewMenu();MenuItem(menu,"导入歌单文件",ImportFile);MenuItem(menu,"导入音乐目录",ImportFolder);MenuItem(menu,"导入音乐文件",ImportAudio);MenuItem(menu,"指定官方下载目录",ChooseSourceFolder);if(owner==null)menu.Show(Cursor.Position);else menu.Show(owner,new Point(0,owner.Height));}
  ContextMenuStrip NewMenu(){return new ContextMenuStrip{BackColor=Color.White,ForeColor=ink,Font=new Font(Font.FontFamily,9),ShowImageMargin=false};}
  void MenuItem(ContextMenuStrip menu,string text,Action action){var item=new ToolStripMenuItem(text){Padding=new Padding(12,6,12,6)};item.Click+=(s,e)=>{if(!busy)Safe(action);};menu.Items.Add(item);}
  void ShowSongMenu(Control owner){if(busy||Selected==null)return;var menu=NewMenu();MenuItem(menu,"关联官方下载文件",BindSource);MenuItem(menu,"打开歌曲官方页",OpenSong);menu.Items.Add(new ToolStripSeparator());MenuItem(menu,"提供单文件解码密钥",ProvideKey);MenuItem(menu,"QQ 客户端补齐本歌单密钥",()=>FetchQQKeys());menu.Items.Add(new ToolStripSeparator());MenuItem(menu,"重新处理这首歌",ForceTrack);menu.Show(owner,new Point(Math.Min(owner.Width-5,100),Math.Min(owner.Height,210)));}
  void GridMenuClick(object s,DataGridViewCellMouseEventArgs e){if(e.Button!=MouseButtons.Right||e.RowIndex<0)return;grid.CurrentCell=grid.Rows[e.RowIndex].Cells[0];ShowSongMenu(grid);}
  void StyleGrid(DataGridView g){g.Dock=DockStyle.Fill;g.BackgroundColor=Color.White;g.BorderStyle=BorderStyle.None;g.AutoGenerateColumns=false;g.AllowUserToAddRows=false;g.AllowUserToDeleteRows=false;g.ReadOnly=true;g.MultiSelect=false;g.SelectionMode=DataGridViewSelectionMode.FullRowSelect;g.RowHeadersVisible=false;g.EnableHeadersVisualStyles=false;g.ColumnHeadersHeight=40;g.ColumnHeadersDefaultCellStyle.BackColor=Color.FromArgb(249,250,252);g.ColumnHeadersDefaultCellStyle.ForeColor=muted;g.ColumnHeadersDefaultCellStyle.Font=new Font(Font.FontFamily,8.5f);g.DefaultCellStyle.SelectionBackColor=UiTheme.Soft;g.DefaultCellStyle.SelectionForeColor=ink;g.DefaultCellStyle.Padding=new Padding(10,0,0,0);g.RowTemplate.Height=48;g.GridColor=Color.FromArgb(243,245,248);g.CellBorderStyle=DataGridViewCellBorderStyle.SingleHorizontal;g.ColumnHeadersBorderStyle=DataGridViewHeaderBorderStyle.None;g.DefaultCellStyle.ForeColor=ink;g.DefaultCellStyle.BackColor=Color.White;g.AlternatingRowsDefaultCellStyle.BackColor=Color.White;g.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill;}
  void Col(DataGridView g,string name,string prop,float weight){g.Columns.Add(new DataGridViewTextBoxColumn{Name=prop,HeaderText=name,DataPropertyName=prop,FillWeight=weight});}
  void PaintStatus(object s,DataGridViewCellPaintingEventArgs e){if(e.RowIndex<0||e.ColumnIndex<0||grid.Columns[e.ColumnIndex].DataPropertyName!="Status")return;e.PaintBackground(e.ClipBounds,true);string value=Convert.ToString(e.FormattedValue);var rect=new Rectangle(e.CellBounds.X+9,e.CellBounds.Y+12,Math.Min(e.CellBounds.Width-16,90),24);e.Graphics.SmoothingMode=System.Drawing.Drawing2D.SmoothingMode.AntiAlias;using(var path=UiTheme.Round(rect,6))using(var brush=new SolidBrush(UiTheme.StatusFill(value)))e.Graphics.FillPath(brush,path);TextRenderer.DrawText(e.Graphics,value,e.CellStyle.Font,rect,UiTheme.StatusColor(value),TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis);e.Handled=true;}
  void ShowLogs(){using(var dialog=new Form{Text="处理日志",Size=new Size(780,500),StartPosition=FormStartPosition.CenterParent,BackColor=background,Font=Font}){var text=new TextBox{Dock=DockStyle.Fill,Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Both,BorderStyle=BorderStyle.None,BackColor=Color.White,ForeColor=ink,Text=log.Text,Font=new Font(Font.FontFamily,9)};dialog.Padding=new Padding(18);dialog.Controls.Add(text);dialog.ShowDialog(this);}}
  void BuildHistory(){mutable.Clear();var shell=Base("处理历史","删除本地音乐后，成功记录仍然保留，新的歌单可以继续复用。");var body=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=3};body.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));body.RowStyles.Add(new RowStyle(SizeType.Absolute,82));body.RowStyles.Add(new RowStyle(SizeType.Absolute,64));body.RowStyles.Add(new RowStyle(SizeType.Percent,100));shell.Controls.Add(body,0,1);var info=new SurfacePanel{Dock=DockStyle.Fill,BackColor=background,Margin=new Padding(0,0,0,14),Padding=new Padding(16,12,16,12)};int total=store.History.Select(h=>h.RelativePath).Distinct().Count();var totalLabel=Label(total+" 首已处理音乐",17,ink,550,32);totalLabel.Location=new Point(16,9);info.Controls.Add(totalLabel);var detail=Label("历史去重 · 多歌单共享文件 · 原路径引用",8.5f,muted,620,28);detail.Location=new Point(16,42);info.Controls.Add(detail);body.Controls.Add(info,0,0);
   var row=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,RowCount=1,Margin=new Padding(0,0,0,14)};row.RowStyles.Add(new RowStyle(SizeType.Percent,100));row.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));row.RowStyles.Add(new RowStyle(SizeType.Percent,100));row.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,148));row.RowStyles.Add(new RowStyle(SizeType.Percent,100));row.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,147));var wrap=InputWrap(historySearch,"search");wrap.Margin=new Padding(0,0,14,0);row.Controls.Add(wrap,0,0);historySearch.TextChanged-=HistoryChanged;historySearch.TextChanged+=HistoryChanged;var root=Button("打开记录目录",()=>OpenFolder(store.Root),140,false);root.Dock=DockStyle.Fill;row.Controls.Add(root,1,0);var clear=Button("清除所选记录",ClearHistoryEntry,140,false);clear.Dock=DockStyle.Fill;row.Controls.Add(clear,2,0);body.Controls.Add(row,0,1);historyGrid.Columns.Clear();StyleGrid(historyGrid);Col(historyGrid,"歌曲","Title",23);Col(historyGrid,"歌手","Artist",17);Col(historyGrid,"平台","Platform",13);Col(historyGrid,"音频参数","Profile",18);Col(historyGrid,"处理时间","ProcessedAt",24);Col(historyGrid,"固定引用路径","RelativePath",35);var surface=new SurfacePanel{Dock=DockStyle.Fill,BackColor=background,Padding=new Padding(8)};surface.Controls.Add(historyGrid);body.Controls.Add(surface,0,2);FilterHistory();}
  void HistoryChanged(object s,EventArgs e){FilterHistory();}
  void ClearHistoryEntry(){var entry=historyGrid.CurrentRow==null?null:historyGrid.CurrentRow.DataBoundItem as HistoryEntry;if(entry==null)return;if(MessageBox.Show(this,"清除后，这条记录不再用于历史去重。音乐文件不会删除。","清除记录",MessageBoxButtons.OKCancel)==DialogResult.OK){store.History.Remove(entry);store.SaveHistory();FilterHistory();RefreshSidebar();}}
  void FilterHistory(){string term=historySearch.Text.Trim();historyGrid.DataSource=new BindingList<HistoryEntry>(store.History.Where(h=>term.Length==0||(h.Title+" "+h.Artist+" "+h.Platform).IndexOf(term,StringComparison.OrdinalIgnoreCase)>=0).Reverse().ToList());}
  SurfacePanel SettingsCard(string title,int height){var panel=new SurfacePanel{Height=height,BackColor=background,Padding=new Padding(18),Margin=new Padding(0,0,0,16)};var label=Label(title,13,ink,700,30);label.Location=new Point(18,10);panel.Controls.Add(label);return panel;}
  void BuildSettings(){mutable.Clear();var shell=Base("设置与帮助","存储、保真处理与使用方式，在这里统一管理。");var scroll=new Panel{Dock=DockStyle.Fill,AutoScroll=true,BackColor=background};shell.Controls.Add(scroll,0,1);var stack=new FlowLayoutPanel{FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoSize=true,Location=Point.Empty,BackColor=background};scroll.Controls.Add(stack);
   var storage=SettingsCard("存储位置",163);var input=InputWrap(output,"folder");output.Text=store.Settings.OutputRoot;input.SetBounds(18,48,600,38);input.Dock=DockStyle.None;storage.Controls.Add(input);var choose=Button("选择导出目录",()=>{using(var d=new FolderBrowserDialog())if(d.ShowDialog(this)==DialogResult.OK)output.Text=d.SelectedPath;},141,false);choose.SetBounds(632,48,145,38);storage.Controls.Add(choose);var note=Label("处理记录独立保存，删除导出音乐不会清除去重历史。",8.5f,muted,730,27);note.Location=new Point(18,91);storage.Controls.Add(note);var data=Label("记录目录："+store.Root,8,muted,760,25);data.Location=new Point(18,117);storage.Controls.Add(data);stack.Controls.Add(storage);
   var quality=SettingsCard("保真与原文件",135);recycle.Text="校验成功后，将对应原音乐文件移入回收站";recycle.Checked=store.Settings.RecycleOriginal;recycle.SetBounds(18,48,760,31);recycle.ForeColor=ink;recycle.BackColor=Color.Transparent;quality.Controls.Add(recycle);flac.Text="将可精确保真的 16 / 24 位无损音频整理为 FLAC";flac.Checked=store.Settings.PreferFlac;flac.SetBounds(18,83,760,31);flac.ForeColor=ink;flac.BackColor=Color.Transparent;quality.Controls.Add(flac);stack.Controls.Add(quality);
   var folders=SettingsCard("指定下载目录",185);sourceDirs.Items.Clear();sourceDirs.Items.AddRange(store.Settings.SourceFolders.Cast<object>().ToArray());sourceDirs.SetBounds(18,48,620,88);sourceDirs.BorderStyle=BorderStyle.None;sourceDirs.BackColor=Color.FromArgb(249,250,252);sourceDirs.ForeColor=ink;folders.Controls.Add(sourceDirs);var add=Button("添加",()=>{using(var d=new FolderBrowserDialog())if(d.ShowDialog(this)==DialogResult.OK&&!sourceDirs.Items.Contains(d.SelectedPath))sourceDirs.Items.Add(d.SelectedPath);},94,false);add.SetBounds(656,48,105,36);folders.Controls.Add(add);var remove=Button("移除",()=>{if(sourceDirs.SelectedIndex>=0)sourceDirs.Items.RemoveAt(sourceDirs.SelectedIndex);},94,false);remove.SetBounds(656,96,105,36);folders.Controls.Add(remove);var hint=Label("只索引你指定的位置，不自动扫描客户端或播放器。",8.5f,muted,730,27);hint.Location=new Point(18,143);folders.Controls.Add(hint);stack.Controls.Add(folders);
   var actions=new FlowLayoutPanel{Height=46,WrapContents=false,Margin=new Padding(0,0,0,16)};actions.Controls.Add(Button("保存设置",SavePreferences,135,true));actions.Controls.Add(Button("打开导出目录",()=>OpenFolder(store.Settings.OutputRoot),146,false));stack.Controls.Add(actions);
   var guide=SettingsCard("从歌单到 Walkman",166);var instructions=Label("01  导入公开歌单，选择官方下载目录。\n02  按原始歌曲 ID 关联；缺失歌曲通过官方客户端下载。\n03  恢复音频载荷并校验，生成音乐与共享播放列表。\n04  将 Music 目录按原结构合并复制到金砖二代。",9,muted,760,112);instructions.Location=new Point(18,45);guide.Controls.Add(instructions);stack.Controls.Add(guide);
   var advanced=SettingsCard("格式与登录状态",153);var info=Label("NCM、QMC、QMC2、musicex V1 均按实际文件结构处理。\n新版 QQ 缺密钥时，在歌曲操作菜单手动提供，或主动授权客户端取密钥。\n默认不读取登录状态；登录令牌不写入设置、历史和日志。\n播放器上的中文 M3U 与专辑封面仍需实机验证。",8.5f,muted,790,100);info.Location=new Point(18,43);advanced.Controls.Add(info);stack.Controls.Add(advanced);
   Action resize=()=>{int width=Math.Max(700,scroll.ClientSize.Width-22);stack.Width=width;foreach(Control c in stack.Controls)c.Width=width;input.Width=Math.Max(380,width-195);choose.Left=width-159;sourceDirs.Width=Math.Max(380,width-165);add.Left=remove.Left=width-136;};scroll.Resize+=(s,e)=>resize();resize();}
  void SavePreferences(){if(string.IsNullOrWhiteSpace(output.Text))throw new InvalidDataException("请选择导出目录");store.Settings.OutputRoot=Path.GetFullPath(output.Text.Trim());store.Settings.RecycleOriginal=recycle.Checked;store.Settings.PreferFlac=flac.Checked;store.Settings.SourceFolders=sourceDirs.Items.Cast<string>().ToList();store.SaveSettings();Append("设置已保存");MessageBox.Show(this,"设置已保存。","音乐助手");}
 }
}
